### ISSUE TITLE
Panic with data that contains null-value fields

### ISSUE THREAD

**Issue by quickshore** [atlasgurus/rulestone#5]
**Steps to reproduce**

1. Add null-value field to any test data, for example to examples/data/data_expression_test0.json:
```
{
  "name": "Frank",
  "age": 20,
  "gender": "male",
  "child": {
    "nested": [
      {
        "age": 5
      },
      {
        "age": 10
      }
    ]
  },
  "some_field": null
}
```

2. Run tests

**Expected**

Tests PASS.

**Actual**

Tests FAILS:

```
--- FAIL: TestFilterApiExpression0 (0.00s)
panic: Should not get here [recovered]
	panic: Should not get here

goroutine 40 [running]:
testing.tRunner.func1.2({0x11e0bc0, 0x1269160})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0x11e0bc0, 0x1269160})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/atlasgurus/rulestone/objectmap.(*ObjectAttributeMapper).buildObjectMap(0xc0004a6b40, {0xc000019390?, 0x5?}, {0x0, 0x0}, {0xc00010ea00?, 0x3, 0x64?}, 0xc00012a230?, 0xc000133d70, ...)
	/Users/avf/projects/rulestone/objectmap/object_attribute_map.go:453 +0x4d8
github.com/atlasgurus/rulestone/objectmap.(*ObjectAttributeMapper).buildObjectMap(0xc0004a6b40, {0x0, 0x0}, {0x11eb260, 0xc0004a9e30}, {0xc00010ea00?, 0x3, 0x64}, 0xc00012a230, 0xc000133d70, ...)
	/Users/avf/projects/rulestone/objectmap/object_attribute_map.go:424 +0x585
github.com/atlasgurus/rulestone/objectmap.(*ObjectAttributeMapper).MapObject(0x126dd20?, {0x11eb260, 0xc0004a9e30}, 0xc000133d40?)
	/Users/avf/projects/rulestone/objectmap/object_attribute_map.go:460 +0xc5
github.com/atlasgurus/rulestone/engine.(*RuleEngine).MatchEvent(0xc000090000, {0x11eb260, 0xc0004a9e30})
	/Users/avf/projects/rulestone/engine/engine_api.go:166 +0xaa
github.com/atlasgurus/rulestone/tests.TestFilterApiExpression0(0xc000502d00)
	/Users/avf/projects/rulestone/tests/engine_api_test.go:25 +0x1c8
testing.tRunner(0xc000502d00, 0x1236610)
	/usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1629 +0x3ea
```

**Comment by quickshore** [comment]
Was fixed.
